# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200)),
                ('article_text', models.TextField()),
                ('article_description', models.TextField()),
                ('article_published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
