# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questscreed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_title', models.CharField(max_length=200)),
                ('quest_city', models.CharField(max_length=200)),
                ('quest_type', models.CharField(max_length=100)),
                ('complexity', models.CharField(max_length=50)),
                ('quest_time', models.DateTimeField()),
                ('min_players', models.IntegerField()),
                ('max_players', models.IntegerField()),
            ],
        ),
    ]
