# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questscreed', '0002_quest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='quest_time',
        ),
        migrations.AddField(
            model_name='quest',
            name='quest_text',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
