# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-29 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questscreed', '0003_auto_20180428_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='quest_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
