# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-29 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questscreed', '0004_auto_20180429_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='quest_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
