# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questscreed', '0008_comment_comment_quest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='questscreed.Quest'),
        ),
    ]
