# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-03 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questscreed', '0010_auto_20180502_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_title', models.CharField(max_length=200)),
                ('stage_question', models.TextField()),
                ('answer_text', models.TextField()),
                ('hint', models.TextField()),
                ('stage_quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='questscreed.Quest')),
            ],
        ),
    ]
