# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questscreed', '0011_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='quest_type',
            field=models.CharField(choices=[('CQ', 'Classical_quest'), ('QE', 'Quest_excursion')], default='QE', max_length=2),
        ),
    ]
