# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questscreed', '0012_auto_20180508_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='complexity',
            field=models.CharField(choices=[('EA', 'Легко'), ('ME', 'Средне'), ('HA', 'Сложно')], default='EA', max_length=2),
        ),
        migrations.AlterField(
            model_name='quest',
            name='quest_type',
            field=models.CharField(choices=[('CQ', 'Классический квест'), ('QE', 'Квест-экскурсия')], default='QE', max_length=2),
        ),
    ]
