# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questscreed', '0014_auto_20180508_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='question_type',
            field=models.CharField(choices=[('QWC', 'Задание с выбором ответа'), ('QWA', 'Задание со свободным вводом ответа'), ('QWP', 'Задание с отправлением изображения'), ('QWL', 'Задание с отправлением координат')], default='QWC', max_length=3),
        ),
    ]
