# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-10 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questscreed', '0015_stage_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('answer_quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questscreed.Quest')),
                ('answer_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questscreed.Stage')),
            ],
        ),
    ]
