# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-11 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questscreed', '0016_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_quest',
        ),
        migrations.AddField(
            model_name='quest',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
