# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-11 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questscreed', '0017_auto_20180511_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='stage_number',
            field=models.TextField(default=1),
        ),
    ]
