# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-12 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questscreed', '0019_auto_20180511_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='quest_cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='quest_type',
            field=models.CharField(choices=[('CQ', 'Классический квест'), ('QE', 'Квест-экскурсия'), ('AQ', 'Авто-квест')], default='QE', max_length=2),
        ),
    ]
