# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-14 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questscreed', '0022_auto_20180513_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='answer_choice_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='answer_choice_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='answer_choice_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='answer_choice_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='answer_right_choice',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
