# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-14 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questscreed', '0023_auto_20180515_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_choice',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='answer_right_choice',
            field=models.IntegerField(null=True),
        ),
    ]
