# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-14 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questscreed', '0024_auto_20180515_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='answer_right_choice',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
