# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-15 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questscreed', '0025_auto_20180515_0111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_login', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('time', models.TimeField()),
                ('stat_quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='questscreed.Quest')),
            ],
        ),
    ]
