# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-15 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questscreed', '0027_auto_20180515_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
