# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-15 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questscreed', '0028_auto_20180515_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='time',
        ),
    ]
