# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-22 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questscreed', '0031_auto_20180515_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='quest_author',
            field=models.CharField(default='admin', max_length=200),
        ),
    ]
