# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-22 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questscreed', '0032_quest_quest_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='answer_variant_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='answer_variant_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='answer_variant_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='answer_variant_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='question_type',
            field=models.CharField(choices=[('QWC', 'Задание с выбором ответа'), ('QWA', 'Задание со свободным вводом ответа'), ('QWP', 'Задание с отправлением изображения'), ('QWE', 'Задание на определение соответствия')], default='QWC', max_length=3),
        ),
    ]
