# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-26 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questscreed', '0033_auto_20180522_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Universary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universary_login', models.CharField(max_length=200)),
                ('balloon', models.BooleanField(default=False)),
                ('text', models.BooleanField(default=False)),
                ('mask', models.BooleanField(default=False)),
                ('send', models.BooleanField(default=False)),
                ('photo', models.BooleanField(default=False)),
            ],
        ),
    ]
