from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^$', views.index, name='index'),
    url(r'^main/', views.main_page, name='main_page'),
    url(r'^universary/pass/(?P<stage_pk>\d+)/$', views.universary_pass, name='universary_pass'),
    url(r'^universary/', views.universary, name='universary'),
    url(r'^moderation/', views.moderation, name='moderation'),
    url(r'^quests/popular/', views.quests_popular, name='quests_popular'),
    url(r'^quests/reverse/', views.quests_reverse, name='quests_reverse'),
    url(r'^quests/', views.quests, name='quests'),
    url(r'^rules/', views.rules, name='rules'),
    url(r'^quest/(?P<pk>\d+)/vote/$', views.quest_vote, name='quest_vote'),
    url(r'^quest/(?P<pk>\d+)/comment/$', views.add_comment_to_quest, name='add_comment_to_quest'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
    url(r'^quest/add/$', views.add_quest, name='add_quest'),
    url(r'^quest/(?P<pk>\d+)/remove/$', views.delete_quest, name='delete_quest'),
    url(r'^quest/(?P<pk>\d+)/edit/stages/$', views.stage_list, name='stage_list'),
    url(r'^quest/(?P<pk>\d+)/stage/add/$', views.stage_add, name='stage_add'),
    url(r'^quest/(?P<pk>\d+)/edit/$', views.quest_edit, name='quest_edit'),
    url(r'^quest/(?P<quest_pk>\d+)/pass/(?P<stage_pk>\d+)/$', views.quest_pass_stage, name='quest_pass_stage'),
    url(r'^quest/(?P<pk>\d+)/pass/last/$', views.quest_pass_last, name='quest_pass_last'),
    url(r'^quest/(?P<pk>\d+)/pass/$', views.quest_pass_index, name='quest_pass_index'),
    url(r'^quest/(?P<pk>\d+)/$', views.quest_detail, name='quest_detail'),
    url(r'^stage/(?P<pk>\d+)/edit/$', views.stage_edit, name='stage_edit'),
    url(r'^news/add/$', views.add_article, name='add_article'),
    url(r'^news/(?P<pk>\d+)/remove/$', views.delete_article, name='delete_article'),
    url(r'^news/(?P<pk>\d+)/edit/$', views.news_edit, name='news_edit'),
    url(r'^news/(?P<pk>\d+)/$', views.news_detail, name='news_detail'),
    url(r'^news/$', views.news, name='news'),
    url(r'^commoncomment/(?P<pk>\d+)/approve/$', views.commoncomment_approve, name='commoncomment_approve'),
	url(r'^commoncomment/(?P<pk>\d+)/remove/$', views.commoncomment_remove, name='commoncomment_remove'),
    url(r'^comment/$', views.add_comment, name='add_comment'),
    url(r'^quest/(?P<pk>\d+)/pass/statistics/$', views.statistics, name='statistics'),
]